DATASET:
  TRAIN:
    TYPE: 'JRDB2022'
    ROOT: 'data/jrdb-pose/' # Root directory of unlabeld videos
    IMG_PREFIX: ''
    ANN: ''
    AUG:
      FLIP: false # Flip. Default: false
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  EVAL:
    TYPE: 'JRDB2022'
    ROOT: 'data/jrdb-pose/' # Root directory of unlabeld videos
    IMG_PREFIX: ''
    ANN: ''

DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48

MODEL:
  TYPE: 'FastPose' # 'SimplePose' or 'FastPose' or 'PoseHighResolutionNet'
  PRETRAINED: 'pretrained_models/jrdb/fastpose_256x192.pth'
  # PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50

LOSS:
  TYPE: 'MSELoss'

DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05

AE:
  Z_DIM: 4
  PRETRAINED_ROOT: 'pretrained_models/wholebodyAE/JRDB2022'
  EPOCH: 20
  LR: 0.00008

AUXNET:
  PRETRAINED_ROOT: 'pretrained_models/auxnet'
  EPOCH: 20
  LR: 0.00008

RETRAIN:
  BATCH_SIZE: 32 # default: 24
  BASE: 25 # default: continual: 25
  OPTIMIZER: 'AdamW' #SGD or Adam or AdamW
  LR: 0.00025 # continual: 0.00025
  ALPHA: 250 # continual: 250
  WEIGHT_DECAY: 0.7 # continual: 0.7
  LR_GAMMA: 0.99 # continual:0.99

VAL:
  FINISH_ACC: 1 # default: 0.75
  BATCH_SIZE: 420 # default: 256
  W_UNC: 0.01
  UNC_LAMBDA: 0.01 # unc weight for coreset sampling
  QUERY_RATIO: [0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.6, 0.8, 1.0] # list of query ratio for evaluation
  # QUERY_RATIO: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0] # for stopping criterion test
  # QUERY_RATIO: [0.05, 0.1, 0.2, 0.4, 0.7, 1.0] # for PCIT/JRDB
  # QUERY_RATIO: [0.01, 1.0] # for debug
  VIS: True