DATASET:
  EVAL:
    TYPE: 'Halo'
    ROOT: './data/HaloPose/' # Root directory of unlabeld videos
    IMG_PREFIX: 'images/val/000522_mpii_test/'
    ANN: 'val_ann/000522_test.json'

RESULT:
  OUTDIR: 'examples/res/' # output-directory

DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48

MODEL:
  TYPE: 'SimplePose'
  PRETRAINED: 'pretrained_models/simple_res50_256x192.pth'
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50

LOSS:
  TYPE: 'MSELoss'

DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05

EVAL:
  BATCH_SIZE: 32