DATASET:
  TRAIN:
    TYPE: 'Posetrack21'
    ROOT: 'data/PoseTrack21/' # Root directory of unlabeld videos
    IMG_PREFIX: ''
    ANN: ''
    AUG:
      FLIP: false # Flip. Default: false
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  EVAL:
    TYPE: 'Posetrack21'
    ROOT: 'data/PoseTrack21/' # Root directory of unlabeld videos
    IMG_PREFIX: ''
    ANN: ''

DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48

MODEL:
  TYPE: 'SimplePose' # 'SimplePose' or 'FastPose' or 'PoseHighResolutionNet'
  # PRETRAINED: 'pretrained_models/posetrack21/simplebaseline_256x192.pth'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50

# MODEL:
#   TYPE: 'PoseHighResolutionNet'
#   PRETRAINED: 'pretrained_models/posetrack21/hrnet_256x192.pth'
#   TRY_LOAD: ''
#   NUM_LAYERS: 50
#   FINAL_CONV_KERNEL: 1
#   PRETRAINED_LAYERS: ['*']
#   STAGE2:
#     NUM_MODULES: 1
#     NUM_BRANCHES: 2
#     NUM_BLOCKS: [4, 4]
#     NUM_CHANNELS: [32, 64]
#     BLOCK: 'BASIC'
#     FUSE_METHOD: 'SUM'
#   STAGE3:
#     NUM_MODULES: 4
#     NUM_BRANCHES: 3
#     NUM_BLOCKS: [4, 4, 4]
#     NUM_CHANNELS: [32, 64, 128]
#     BLOCK: 'BASIC'
#     FUSE_METHOD: 'SUM'
#   STAGE4:
#     NUM_MODULES: 3
#     NUM_BRANCHES: 4
#     NUM_BLOCKS: [4, 4, 4, 4]
#     NUM_CHANNELS: [32, 64, 128, 256]
#     BLOCK: 'BASIC'
#     FUSE_METHOD: 'SUM'

LOSS:
  TYPE: 'MSELoss'

DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05

AE:
  Z_DIM: 3
  PRETRAINED_ROOT: 'pretrained_models/wholebodyAE'
  EPOCH: 25

RETRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 50 # default: 50
  EPOCH: 15 # default: 15
  ACCURACY_THRES: 1
  OPTIMIZER: 'Adam' #SGD or Adam
  LR: 0.0005 #0.001 or 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120

VAL:
  BATCH_SIZE: 80 # default: 70
  QUERY_RATIO: 0.05 # defaunlt: 0.05
  VIS: True