DATASET:
  TRAIN:
    TYPE: 'Posetrack21'
    ROOT: 'data/PoseTrack21/' # Root directory of unlabeld videos misc: 'data/PoseTrack21/'
    IMG_PREFIX: ''
    ANN: ''
    AUG:
      FLIP: false # Flip. Default: false
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  EVAL:
    TYPE: 'Posetrack21'
    ROOT: 'data/PoseTrack21/' # Root directory of unlabeld videos
    IMG_PREFIX: ''
    ANN: ''

DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48

MODEL:
  TYPE: 'SimplePose' # 'SimplePose' or 'FastPose' or 'PoseHighResolutionNet'
  PRETRAINED: 'pretrained_models/posetrack21/simplebaseline_256x192.pth'
  # PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50

LOSS:
  TYPE: 'MSELoss'

DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05

AE:
  Z_DIM: 3
  PRETRAINED_ROOT: 'pretrained_models/wholebodyAE'
  EPOCH: 25

RETRAIN:
  BATCH_SIZE: 24 # default: 24
  EPOCH: 10 # default: 10
  ACCURACY_THRES: 1
  OPTIMIZER: 'AdamW' #SGD or Adam or AdamW
  LR: 0.00025 # 0.0002
  ALPHA: 0.5

VAL:
  FINISH_ACC: 0.99
  BATCH_SIZE: 256 # default: 256
  W_UNC: 200
  UNC_LAMBDA: 0 # unc weight for coreset sampling
  QUERY_RATIO: [0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.6, 0.8, 1.0] # list of query ratio for evaluation
  # QUERY_RATIO: [0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.5, 0.75, 1.0] # for PCIT
  # QUERY_RATIO: [0.05, 0.4, 0.7, 1.0] # for debug
  VIS: True