DATASET:
  TRAIN:
    TYPE: 'Posetrack21'
    ROOT: './data/PoseTrack21/'
    IMG_PREFIX: 'images/train'
    ANN: 'activelearning/train/000000_integrated_train.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  VAL:
    TYPE: 'Posetrack21'
    ROOT: './data/PoseTrack21'
    IMG_PREFIX: 'images/train'
    ANN: 'activelearning/train_val/000000_integrated_train_val.json'

DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48

MODEL:
  TYPE: 'PoseHighResolutionNet'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_LAYERS: 50
  FINAL_CONV_KERNEL: 1
  PRETRAINED_LAYERS: ['*']
  STAGE2:
    NUM_MODULES: 1
    NUM_BRANCHES: 2
    NUM_BLOCKS: [4, 4]
    NUM_CHANNELS: [32, 64]
    BLOCK: 'BASIC'
    FUSE_METHOD: 'SUM'
  STAGE3:
    NUM_MODULES: 4
    NUM_BRANCHES: 3
    NUM_BLOCKS: [4, 4, 4]
    NUM_CHANNELS: [32, 64, 128]
    BLOCK: 'BASIC'
    FUSE_METHOD: 'SUM'
  STAGE4:
    NUM_MODULES: 3
    NUM_BRANCHES: 4
    NUM_BLOCKS: [4, 4, 4, 4]
    NUM_CHANNELS: [32, 64, 128, 256]
    BLOCK: 'BASIC'
    FUSE_METHOD: 'SUM'

LOSS:
  TYPE: 'MSELoss'

DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05

TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 170 # dl21ではちょうど170ぐらい
  BEGIN_EPOCH: 0
  END_EPOCH: 270
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 170
  - 200
  DPG_MILESTONE: 210
  DPG_STEP:
  - 230
  - 250

VAL:
  BATCH_SIZE: 350